theme: minima
title: Aryan Rathnam
author: GitHub User
email: arathnam824@gmail.com


# social links
twitter_username: AryanRathnam # DO NOT include the @ character, or else the build will fail!
github_username:  arathnam824 # DO NOT include the @ character, or else the build will fail!

description: 3rd place New Jersey Science Olympiad Experimental Design. 4th place New Jersey Science Olympiad Meteorology.

show_excerpts: true # set to false to remove excerpts on the homepage
